sonar.projectKey=Scry
sonar.projectName=TableOS Scry
sonar.host.url=http://localhost:9000
sonar.sources=scripts,styles
sonar.exclusions=**/node_modules/**,**/* - Copy*.js
sonar.sourceEncoding=UTF-8
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
